apiVersion: v1
kind: Namespace
metadata:
  name: interns-demo
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: app-config
  namespace: interns-demo
data:
  HELLO_WHO: "Interns"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: interns-demo
  namespace: interns-demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: interns-demo
  template:
    metadata:
      labels:
        app: interns-demo
    spec:
      containers:
        - name: interns-demo
          envFrom:
            - configMapRef:
                name: app-config
          image: quay.io/pb82/interns-demo:latest
          ports:
            - containerPort: 3000
---
kind: Service
apiVersion: v1
metadata:
  name: interns-demo
  namespace: interns-demo
spec:
  ports:
    - protocol: TCP
      port: 3000
      targetPort: 3000
      name: http
  type: ClusterIP
  selector:
    app: interns-demo
---
kind: Route
apiVersion: route.openshift.io/v1
metadata:
  name: interns-demo
  namespace: interns-demo
spec:
  to:
    kind: Service
    name: interns-demo
  port:
    targetPort: http
  wildcardPolicy: None
